# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "adc1b15bae96290aba407442c7c7dcff"
name = "dropsaas-app"
application_url = "https://securities-martin-glance-mesh.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update", "products/create", "products/update" ]
  uri = "/webhooks/products"

  [[webhooks.subscriptions]]
  topics = [ "orders/create", "orders/updated" ]
  uri = "/webhooks/orders"

  [[webhooks.subscriptions]]
  topics = [ "fulfillments/create", "fulfillments/update" ]
  uri = "/webhooks/fulfillments"

  [[webhooks.subscriptions]]
  topics = [ "fulfillment_events/create" ]
  uri = "/webhooks/fulfillment-events"

  [[webhooks.subscriptions]]
  topics = [ "orders/fulfilled", "orders/partially_fulfilled" ]
  uri = "/webhooks/orders/fulfillment"


[access_scopes]
# Learn more at https://gods-equilibrium-answering-international.trycloudflare.com 
scopes = "write_products,read_orders,write_orders,read_fulfillments,write_fulfillments"


[auth]
redirect_urls = [ "https://securities-martin-glance-mesh.trycloudflare.com/auth/callback" ]
