# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "adc1b15bae96290aba407442c7c7dcff"
name = "dropsaas-app"
application_url = "https://acm-evidence-webpage-lobby.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-04"

  [[webhooks.subscriptions]]
  topics = [ "orders/fulfilled", "orders/partially_fulfilled" ]
  uri = "/webhooks/orders/fulfillment"

  [[webhooks.subscriptions]]
  topics = [ "orders/create", "orders/updated" ]
  uri = "/webhooks/orders"

  [[webhooks.subscriptions]]
  topics = [ "fulfillment_events/create" ]
  uri = "/webhooks/fulfillment-events"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "fulfillments/create", "fulfillments/update" ]
  uri = "/webhooks/fulfillments"

  [[webhooks.subscriptions]]
  topics = [ "products/create", "products/update", "app/scopes_update" ]
  uri = "/webhooks/products"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_fulfillments,read_orders,write_fulfillments,write_orders,write_products"

[auth]
redirect_urls = [
  "https://acm-evidence-webpage-lobby.trycloudflare.com/auth/callback"
]
